# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
        ('globaly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='SLUG_LABEL')),
                ('meta_title', models.CharField(max_length=255, verbose_name='META_TITLE_LABEL')),
                ('meta_description', models.CharField(blank=True, max_length=156, verbose_name='META_DESCRIPTION_LABEL')),
                ('publish', models.BooleanField(default=True, verbose_name='PUBLISH_LABEL')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='NAME_LABEL')),
                ('post_type', models.CharField(choices=[(b'post', b'Blog Post'), (b'page', b'Page'), (b'game', b'Game'), (b'game_engine', b'Game Engine'), (b'video', b'Video'), (b'forum', b'Forum')], default=b'post', max_length=20)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories_parent', to='posts.PostCategory', verbose_name='PARENT_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'CATEGORY_TITLE_PLURAL',
                'db_table': 'posts_categories',
                'verbose_name': 'CATEGORY_TITLE',
            },
        ),
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='SLUG_LABEL')),
                ('meta_title', models.CharField(max_length=255, verbose_name='META_TITLE_LABEL')),
                ('meta_description', models.CharField(blank=True, max_length=156, verbose_name='META_DESCRIPTION_LABEL')),
                ('publish', models.BooleanField(default=True, verbose_name='PUBLISH_LABEL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='TITLE_LABEL')),
                ('excerpt', models.TextField(blank=True, verbose_name='EXCERPT_LABEL')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT_LABEL')),
                ('is_featured', models.BooleanField(default=True, verbose_name='IS_FEATURED_LABEL')),
                ('is_on_feed', models.BooleanField(default=True, verbose_name='IS_ON_FEED_LABEL')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='THUNBNAIL_LABEL')),
                ('thumbnail_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='ATL_TEXT_LABEL')),
                ('featured_image', models.TextField(blank=True, null=True, verbose_name='FEATURED_IMAGE_LABEL')),
                ('featured_image_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='ATL_TEXT_LABEL')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('featured_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Featured Start Date')),
                ('featured_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Featured End Date')),
                ('post_type', models.CharField(choices=[(b'post', b'Blog Post'), (b'page', b'Page'), (b'game', b'Game'), (b'game_engine', b'Game Engine'), (b'video', b'Video'), (b'forum', b'Forum')], default=b'post', max_length=20)),
                ('album', models.ManyToManyField(blank=True, related_name='post_item_related_albums', to='media.MediaAlbum', verbose_name='MEDIA_ALBUM_TITLE_PLURAL')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_item_autor', to=settings.AUTH_USER_MODEL, verbose_name='AUTOR_LABEL')),
                ('categories', models.ManyToManyField(blank=True, related_name='post_item_related_categories', to='posts.PostCategory', verbose_name='BLOG_CATEGORY_TITLE_PLURAL')),
                ('related_posts', models.ManyToManyField(blank=True, related_name='_postitem_related_posts_+', to='posts.PostItem', verbose_name='RELATED_ARTICLES_LABEL')),
                ('tags', models.ManyToManyField(blank=True, related_name='post_item_related_tags', to='globaly.GlobalyTags', verbose_name='GLOBALY_TAG_TITLE_PLURAL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'POST_ITEM_TITLE_PLURAL',
                'db_table': 'posts_items',
                'verbose_name': 'POST_ITEM_TITLE',
            },
        ),
    ]
