# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globaly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('title', models.CharField(blank=True, max_length=255, unique=True, verbose_name='TITLE_LABEL')),
                ('publish', models.BooleanField(default=True, verbose_name='PUBLISH_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'MEDIA_ALBUM_TITLE_PLURAL',
                'db_table': 'media_album',
                'verbose_name': 'MEDIA_ALBUM_TITLE',
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='TITLE_LABEL')),
                ('image', models.FileField(blank=True, upload_to=b'uploads/', verbose_name='IMAGE_LABEL')),
                ('rating', models.IntegerField(default=0, verbose_name='RATTING_LABEL')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT_LABEL')),
                ('album', models.ManyToManyField(blank=True, related_name='media_image_related_albums', to='media.MediaAlbum', verbose_name='MEDIA_ALBUM_TITLE_PLURAL')),
                ('tags', models.ManyToManyField(blank=True, related_name='media_image_related_tags', to='globaly.GlobalyTags', verbose_name='GLOBALY_TAG_TITLE_PLURAL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'MEDIA_IMAGE_TITLE_PLURAL',
                'db_table': 'media_image',
                'verbose_name': 'MEDIA_IMAGE_TITLE',
            },
        ),
    ]
