# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('publish', models.BooleanField(default=True, verbose_name='PUBLISH_LABEL')),
                ('autor_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='RELATED_ITEM_LABEL')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='MESSAGE_LABEL')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[(b'published', b'Published'), (b'trashed', b'Trashed'), (b'blocked', b'Blocked'), (b'deleted', b'Deleted')], default=b'published', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP_ADDRESS_LABEL')),
                ('post_type', models.CharField(choices=[(b'post', b'Blog Post'), (b'page', b'Page'), (b'video', b'Video'), (b'forum', b'Forum')], default=b'post', max_length=20)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('autor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='CONTENT_TYPE_LABEL')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_related_parent', to='comments.Comments', verbose_name='PARENT_LABEL')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_related_target', to='posts.PostItem', verbose_name='TARGET_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'COMMENTS_TITLE_PLURAL',
                'db_table': 'comments',
                'verbose_name': 'COMMENTS_TITLE',
            },
        ),
    ]
