# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalyTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='SLUG_LABEL')),
                ('meta_title', models.CharField(max_length=255, verbose_name='META_TITLE_LABEL')),
                ('meta_description', models.CharField(blank=True, max_length=156, verbose_name='META_DESCRIPTION_LABEL')),
                ('publish', models.BooleanField(default=True, verbose_name='PUBLISH_LABEL')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='NAME_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'GLOBALY_TAG_TITLE_PLURAL',
                'db_table': 'globaly_tags',
                'verbose_name': 'GLOBALY_TAG_TITLE',
            },
        ),
    ]
