
INSTALLED_APPS = (
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_markup',
    'captcha',
    'widget_tweaks',
    'mptt',
    #'form_utils',
    'user',
    'user_site',
    'rss',
    'sitemap',
    'utilities',   
    'globaly',   
    'posts',
    'media',
    'global_config',
    'navigation',
    #'contact_form',
    'comments',   

)
